<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output encoding="utf-8" indent="yes"/>

    <xsl:template name="phonePrefixOptions">
        <!--
            Note the SFCC xmlns attribute of the root (<option>) element of the template.
            All templates must be in same namespace if you want produce an XML without
            "xmlns" attributes from child includes.
        -->
        <options xmlns="http://www.demandware.com/xml/form/2008-04-19">
            <option optionid='us' value='+1' label='country.us.code'/>
            <option optionid='ru' value='+7' label='country.ru.code'/>
            <option optionid='eg' value='+20' label='country.eg.code'/>
            <option optionid='za' value='+27' label='country.za.code'/>
            <option optionid='gr' value='+30' label='country.gr.code'/>
            <option optionid='nl' value='+31' label='country.nl.code'/>
            <option optionid='be' value='+32' label='country.be.code'/>
            <option optionid='fr' value='+33' label='country.fr.code'/>
            <option optionid='es' value='+34' label='country.es.code'/>
            <option optionid='hu' value='+36' label='country.hu.code'/>
            <option optionid='it' value='+39' label='country.it.code'/>
            <option optionid='ro' value='+40' label='country.ro.code'/>
            <option optionid='ch' value='+41' label='country.ch.code'/>
            <option optionid='at' value='+43' label='country.at.code'/>
            <option optionid='gb' value='+44' label='country.gb.code'/>
            <option optionid='dk' value='+45' label='country.dk.code'/>
            <option optionid='se' value='+46' label='country.se.code'/>
            <option optionid='no' value='+47' label='country.no.code'/>
            <option optionid='pl' value='+48' label='country.pl.code'/>
            <option optionid='de' value='+49' label='country.de.code'/>
            <option optionid='pe' value='+51' label='country.pe.code'/>
            <option optionid='mx' value='+52' label='country.mx.code'/>
            <option optionid='cu' value='+53' label='country.cu.code'/>
            <option optionid='ar' value='+54' label='country.ar.code'/>
            <option optionid='br' value='+55' label='country.br.code'/>
            <option optionid='cl' value='+56' label='country.cl.code'/>
            <option optionid='co' value='+57' label='country.co.code'/>
            <option optionid='ve' value='+58' label='country.ve.code'/>
            <option optionid='my' value='+60' label='country.my.code'/>
            <option optionid='au' value='+61' label='country.au.code'/>
            <option optionid='id' value='+62' label='country.id.code'/>
            <option optionid='ph' value='+63' label='country.ph.code'/>
            <option optionid='nz' value='+64' label='country.nz.code'/>
            <option optionid='sg' value='+65' label='country.sg.code'/>
            <option optionid='th' value='+66' label='country.th.code'/>
            <option optionid='jp' value='+81' label='country.jp.code'/>
            <option optionid='kr' value='+82' label='country.kr.code'/>
            <option optionid='vn' value='+84' label='country.vn.code'/>
            <option optionid='cn' value='+86' label='country.cn.code'/>
            <option optionid='tr' value='+90' label='country.tr.code'/>
            <option optionid='in' value='+91' label='country.in.code'/>
            <option optionid='pk' value='+92' label='country.pk.code'/>
            <option optionid='af' value='+93' label='country.af.code'/>
            <option optionid='lk' value='+94' label='country.lk.code'/>
            <option optionid='mm' value='+95' label='country.mm.code'/>
            <option optionid='ir' value='+98' label='country.ir.code'/>
            <option optionid='ma' value='+212' label='country.ma.code'/>
            <option optionid='dz' value='+213' label='country.dz.code'/>
            <option optionid='tn' value='+216' label='country.tn.code'/>
            <option optionid='ly' value='+218' label='country.ly.code'/>
            <option optionid='gm' value='+220' label='country.gm.code'/>
            <option optionid='sn' value='+221' label='country.sn.code'/>
            <option optionid='mr' value='+222' label='country.mr.code'/>
            <option optionid='ml' value='+223' label='country.ml.code'/>
            <option optionid='gn' value='+224' label='country.gn.code'/>
            <option optionid='ci' value='+225' label='country.ci.code'/>
            <option optionid='bf' value='+226' label='country.bf.code'/>
            <option optionid='ne' value='+227' label='country.ne.code'/>
            <option optionid='tg' value='+228' label='country.tg.code'/>
            <option optionid='bj' value='+229' label='country.bj.code'/>
            <option optionid='mu' value='+230' label='country.mu.code'/>
            <option optionid='lr' value='+231' label='country.lr.code'/>
            <option optionid='sl' value='+232' label='country.sl.code'/>
            <option optionid='gh' value='+233' label='country.gh.code'/>
            <option optionid='ng' value='+234' label='country.ng.code'/>
            <option optionid='td' value='+235' label='country.td.code'/>
            <option optionid='cf' value='+236' label='country.cf.code'/>
            <option optionid='cm' value='+237' label='country.cm.code'/>
            <option optionid='cv' value='+238' label='country.cv.code'/>
            <option optionid='st' value='+239' label='country.st.code'/>
            <option optionid='gq' value='+240' label='country.gq.code'/>
            <option optionid='ga' value='+241' label='country.ga.code'/>
            <option optionid='cg' value='+242' label='country.cg.code'/>
            <option optionid='cd' value='+243' label='country.cd.code'/>
            <option optionid='ao' value='+244' label='country.ao.code'/>
            <option optionid='gw' value='+245' label='country.gw.code'/>
            <option optionid='sc' value='+248' label='country.sc.code'/>
            <option optionid='sd' value='+249' label='country.sd.code'/>
            <option optionid='rw' value='+250' label='country.rw.code'/>
            <option optionid='et' value='+251' label='country.et.code'/>
            <option optionid='so' value='+252' label='country.so.code'/>
            <option optionid='dj' value='+253' label='country.dj.code'/>
            <option optionid='ke' value='+254' label='country.ke.code'/>
            <option optionid='tz' value='+255' label='country.tz.code'/>
            <option optionid='ug' value='+256' label='country.ug.code'/>
            <option optionid='bi' value='+257' label='country.bi.code'/>
            <option optionid='mz' value='+258' label='country.mz.code'/>
            <option optionid='zm' value='+260' label='country.zm.code'/>
            <option optionid='mg' value='+261' label='country.mg.code'/>
            <option optionid='re' value='+262' label='country.re.code'/>
            <option optionid='zw' value='+263' label='country.zw.code'/>
            <option optionid='na' value='+264' label='country.na.code'/>
            <option optionid='mw' value='+265' label='country.mw.code'/>
            <option optionid='ls' value='+266' label='country.ls.code'/>
            <option optionid='bw' value='+267' label='country.bw.code'/>
            <option optionid='sz' value='+268' label='country.sz.code'/>
            <option optionid='km' value='+269' label='country.km.code'/>
            <option optionid='yt' value='+269' label='country.yt.code'/>
            <option optionid='sh' value='+290' label='country.sh.code'/>
            <option optionid='er' value='+291' label='country.er.code'/>
            <option optionid='aw' value='+297' label='country.aw.code'/>
            <option optionid='fo' value='+298' label='country.fo.code'/>
            <option optionid='gl' value='+299' label='country.gl.code'/>
            <option optionid='gi' value='+350' label='country.gi.code'/>
            <option optionid='pt' value='+351' label='country.pt.code'/>
            <option optionid='lu' value='+352' label='country.lu.code'/>
            <option optionid='ie' value='+353' label='country.ie.code'/>
            <option optionid='is' value='+354' label='country.is.code'/>
            <option optionid='al' value='+355' label='country.al.code'/>
            <option optionid='mt' value='+356' label='country.mt.code'/>
            <option optionid='cy' value='+357' label='country.cy.code'/>
            <option optionid='fi' value='+358' label='country.fi.code'/>
            <option optionid='bg' value='+359' label='country.bg.code'/>
            <option optionid='lt' value='+370' label='country.lt.code'/>
            <option optionid='lv' value='+371' label='country.lv.code'/>
            <option optionid='ee' value='+372' label='country.ee.code'/>
            <option optionid='md' value='+373' label='country.md.code'/>
            <option optionid='am' value='+374' label='country.am.code'/>
            <option optionid='by' value='+375' label='country.by.code'/>
            <option optionid='ad' value='+376' label='country.ad.code'/>
            <option optionid='mc' value='+377' label='country.mc.code'/>
            <option optionid='sm' value='+378' label='country.sm.code'/>
            <option optionid='va' value='+379' label='country.va.code'/>
            <option optionid='ua' value='+380' label='country.ua.code'/>
            <option optionid='cs' value='+381' label='country.cs.code'/>
            <option optionid='me' value='+382' label='country.me.code'/>
            <option optionid='hr' value='+385' label='country.hr.code'/>
            <option optionid='si' value='+386' label='country.si.code'/>
            <option optionid='ba' value='+387' label='country.ba.code'/>
            <option optionid='mk' value='+389' label='country.mk.code'/>
            <option optionid='cz' value='+420' label='country.cz.code'/>
            <option optionid='sk' value='+421' label='country.sk.code'/>
            <option optionid='li' value='+423' label='country.li.code'/>
            <option optionid='bz' value='+501' label='country.bz.code'/>
            <option optionid='gt' value='+502' label='country.gt.code'/>
            <option optionid='sv' value='+503' label='country.sv.code'/>
            <option optionid='hn' value='+504' label='country.hn.code'/>
            <option optionid='ni' value='+505' label='country.ni.code'/>
            <option optionid='cr' value='+506' label='country.cr.code'/>
            <option optionid='pa' value='+507' label='country.pa.code'/>
            <option optionid='pm' value='+508' label='country.pm.code'/>
            <option optionid='ht' value='+509' label='country.ht.code'/>
            <option optionid='gp' value='+590' label='country.gp.code'/>
            <option optionid='bl' value='+590' label='country.bl.code'/>
            <option optionid='sx' value='+590' label='country.sx.code'/>
            <option optionid='bo' value='+591' label='country.bo.code'/>
            <option optionid='gy' value='+592' label='country.gy.code'/>
            <option optionid='ec' value='+593' label='country.ec.code'/>
            <option optionid='gf' value='+594' label='country.gf.code'/>
            <option optionid='py' value='+595' label='country.py.code'/>
            <option optionid='mq' value='+596' label='country.mq.code'/>
            <option optionid='sr' value='+597' label='country.sr.code'/>
            <option optionid='uy' value='+598' label='country.uy.code'/>
            <option optionid='an' value='+599' label='country.an.code'/>
            <option optionid='tl' value='+670' label='country.tl.code'/>
            <option optionid='nf' value='+672' label='country.nf.code'/>
            <option optionid='bn' value='+673' label='country.bn.code'/>
            <option optionid='nr' value='+674' label='country.nr.code'/>
            <option optionid='pg' value='+675' label='country.pg.code'/>
            <option optionid='to' value='+676' label='country.to.code'/>
            <option optionid='sb' value='+677' label='country.sb.code'/>
            <option optionid='vu' value='+678' label='country.vu.code'/>
            <option optionid='fj' value='+679' label='country.fj.code'/>
            <option optionid='pw' value='+680' label='country.pw.code'/>
            <option optionid='wf' value='+681' label='country.wf.code'/>
            <option optionid='ck' value='+682' label='country.ck.code'/>
            <option optionid='nu' value='+683' label='country.nu.code'/>
            <option optionid='ws' value='+685' label='country.ws.code'/>
            <option optionid='ki' value='+686' label='country.ki.code'/>
            <option optionid='nc' value='+687' label='country.nc.code'/>
            <option optionid='tv' value='+688' label='country.tv.code'/>
            <option optionid='pf' value='+689' label='country.pf.code'/>
            <option optionid='tk' value='+690' label='country.tk.code'/>
            <option optionid='fm' value='+691' label='country.fm.code'/>
            <option optionid='mh' value='+692' label='country.mh.code'/>
            <option optionid='kp' value='+850' label='country.kp.code'/>
            <option optionid='hk' value='+852' label='country.hk.code'/>
            <option optionid='mo' value='+853' label='country.mo.code'/>
            <option optionid='kh' value='+855' label='country.kh.code'/>
            <option optionid='la' value='+856' label='country.la.code'/>
            <option optionid='bd' value='+880' label='country.bd.code'/>
            <option optionid='tw' value='+886' label='country.tw.code'/>
            <option optionid='mv' value='+960' label='country.mv.code'/>
            <option optionid='lb' value='+961' label='country.lb.code'/>
            <option optionid='jo' value='+962' label='country.jo.code'/>
            <option optionid='sy' value='+963' label='country.sy.code'/>
            <option optionid='iq' value='+964' label='country.iq.code'/>
            <option optionid='kw' value='+965' label='country.kw.code'/>
            <option optionid='sa' value='+966' label='country.sa.code'/>
            <option optionid='ye' value='+967' label='country.ye.code'/>
            <option optionid='om' value='+968' label='country.om.code'/>
            <option optionid='ps' value='+970' label='country.ps.code'/>
            <option optionid='ae' value='+971' label='country.ae.code'/>
            <option optionid='il' value='+972' label='country.il.code'/>
            <option optionid='bh' value='+973' label='country.bh.code'/>
            <option optionid='qa' value='+974' label='country.qa.code'/>
            <option optionid='bt' value='+975' label='country.bt.code'/>
            <option optionid='mn' value='+976' label='country.mn.code'/>
            <option optionid='np' value='+977' label='country.np.code'/>
            <option optionid='tj' value='+992' label='country.tj.code'/>
            <option optionid='tm' value='+993' label='country.tm.code'/>
            <option optionid='az' value='+994' label='country.az.code'/>
            <option optionid='ge' value='+995' label='country.ge.code'/>
            <option optionid='kg' value='+996' label='country.kg.code'/>
            <option optionid='uz' value='+998' label='country.uz.code'/>
        </options>
    </xsl:template>
</xsl:stylesheet>
